name: Update Hosts

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Update Host
        run: |
          pwd
          python ./main.py

      - name: Commit and push changes
        uses: Automattic/action-commit-to-branch@master
        with:
          branch: 'main'
          commit_message: 'update hosts'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

